# Site settings
title: Hack Im Pott
email: hip@chaospott.de
description: > # this means to ignore newlines until "baseurl:"
  hack im pott, an workshop focused event, located in the ruhr area, germany.
baseurl: "" 
url: "http://hackimpott.de"
twitter_username: hackimpott

# Build settings
markdown: kramdown
