# Site settings
title: Hack Im Pott
email: hip@chaospott.de
description: > # this means to ignore newlines until "baseurl:"
  hack im pott, an event based in the ruhrgebiet, germany, focusing on workshops
baseurl: "" 
url: "http://hackimpott.de"
twitter_username: hackimpott

# Build settings
markdown: kramdown
