# Site settings
title: Hack Im Pott
email: tickets@chaospott.de
description: > # this means to ignore newlines until "baseurl:"
  hack im pott, a workshop focused event, located in the ruhr area, germany.
baseurl: ""
url: "https://hackimpott.de"
twitter_username: hackimpott

# Build settings
markdown: kramdown
